import Link from "next/link";
import "./globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next JS Tutorial - Code Evolution",
    template: "%s | Codevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="header">
          <Link href="/" className="logo">
            CompanyLogo
          </Link>
          <div className="header-right">
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/blog">Blog</Link>
            <Link href="/products">Products</Link>
            <Link href="/docs">Document</Link>
            <Link href="/login">Login</Link>
            <Link href="/complex-dashboard">Register</Link>
          </div>
        </header>

        <div className="container">{children}</div>

        <footer>
          <h5>Footer</h5>
        </footer>
      </body>
    </html>
  );
}
